services:
  backend:
    build: 
      args:
        - user=butachi
        - uid=1000
      context: .
      dockerfile: ./${DIR_APP}/Dockerfile
      target: ${DIR_APP}
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 &&  php-fpm"
    restart: unless-stopped
    volumes:
      - ./${DIR_APP}/public:/usr/src/public
      - ./${DIR_APP}/app:/usr/src/app
      - ./${DIR_APP}/config:/usr/src/config
      - ./${DIR_APP}/database:/usr/src/database
      - ./${DIR_APP}/routes:/usr/src/routes
      - ./${DIR_APP}/storage:/usr/src/storage
      - ./${DIR_APP}/bootstrap:/usr/src/bootstrap
      - ./${DIR_APP}/tests:/usr/src/tests
      - ./${DIR_APP}/composer.json:/usr/src/composer.json
      - ./${DIR_APP}/composer.lock:/usr/src/composer.lock
      - ./${DIR_APP}/.env:/usr/src/.env
      - ./deployment/config/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - migrate
      - mysql
      - redis
  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    ports:
      - "63790:6379"
  mysql:
    build: 
      args:
        - password=${DB_PASSWORD}
      context: .
      dockerfile: ./Dockerfile.mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  migrate:
    build: 
      args:
        - user=butachi
        - uid=1000
      context: .
      dockerfile: ./${DIR_APP}/Dockerfile
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && php /usr/src/artisan migrate --force"
    restart: no
    depends_on:
      - mysql
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./${DIR_APP}:/usr/src
      - ./deployment/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ${DIR_APP}
  scheduler:
    build: 
      args:
        - user=butachi
        - uid=1000
      context: .
      dockerfile: ./${DIR_APP}/Dockerfile
      target: scheduler
    restart: unless-stopped
    volumes:
      - ./${DIR_APP}/app:/usr/src/app
      - ./${DIR_APP}/config:/usr/src/config
      - ./${DIR_APP}/database:/usr/src/database
      - ./${DIR_APP}/routes:/usr/src/routes
      - ./${DIR_APP}/storage:/usr/src/storage
      - ./${DIR_APP}/tests:/usr/src/tests
      - ./${DIR_APP}/composer.json:/usr/src/composer.json
      - ./${DIR_APP}/composer.lock:/usr/src/composer.lock
      - ./${DIR_APP}/.env:/usr/src/.env
    depends_on:
      - migrate
      - mysql
      - redis
  worker:
    build: 
      args:
        - user=butachi
        - uid=1000
      context: .
      dockerfile: ./${DIR_APP}/Dockerfile
      target: worker
    restart: unless-stopped
    volumes:
      - ./${DIR_APP}/app:/usr/src/app
      - ./${DIR_APP}/config:/usr/src/config
      - ./${DIR_APP}/database:/usr/src/database
      - ./${DIR_APP}/routes:/usr/src/routes
      - ./${DIR_APP}/storage:/usr/src/storage
      - ./${DIR_APP}/tests:/usr/src/tests
      - ./${DIR_APP}/composer.json:/usr/src/composer.json
      - ./${DIR_APP}/composer.lock:/usr/src/composer.lock
      - ./${DIR_APP}/.env:/usr/src/.env
    depends_on:
      - migrate
      - mysql
      - redis
  update:
    build: 
      args:
        - user=butachi
        - uid=1000
      context: .
      dockerfile: ./${DIR_APP}/Dockerfile
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./update.sh"
    restart: no
    volumes:
      - ./${DIR_APP}/composer.json:/usr/src/composer.json
      - ./${DIR_APP}/composer.lock:/usr/src/composer.lock
      - ./${DIR_APP}/.env:/usr/src/.env
      - ./deployment/bin/update.sh:/usr/src/update.sh
    depends_on:
      - mysql